applications:
  handler: src/functions/api/applications.handler
  events:
    - http:
        path: applications
        method: get
        authorizer: verifyToken
        cors: true 
    - http:
        path: applications/{id}
        method: get
        authorizer: verifyToken
        cors: true 
    - http:
        path: applications
        method: post
        authorizer: verifyToken
        cors: true  
    - http:
        path: applications
        method: put
        authorizer: verifyToken
        cors: true 
    - http:
        path: applications/{id}
        method: delete
        authorizer: verifyToken
        cors: true