products:
  handler: src/functions/api/products.handler
  events:
    - http:
        path: products
        method: get
        authorizer: verifyToken
        cors: true 
    - http:
        path: products/{id}
        method: get
        authorizer: verifyToken
        cors: true 
    - http:
        path: products/all
        method: get
        authorizer: verifyToken
        cors: true
    - http:
        path: products
        method: post
        authorizer: verifyToken
        cors: true  
    - http:
        path: products
        method: put
        authorizer: verifyToken
        cors: true 
    - http:
        path: products/{id}
        method: delete
        authorizer: verifyToken
        cors: true
